on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install vsce
        run: npm install -g vsce

      - name: Install dependencies
        run: npm install

      - name: Publish Theme
        run: vsce publish --pat ${{ secrets.VSCE_PAT }}
